#!/bin/sh

files=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(cpp|hpp)$' || true)

if [ -z "$files" ]; then
    exit 0
fi

echo "formatting staged files"
echo "$files" | xargs clang-format -i --style=file
echo "$files" | xargs git add
echo "files re-staged"
